# Generated by Django 4.1.3 on 2022-11-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
