# Generated by Django 4.1.3 on 2022-11-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.produto'),
        ),
    ]
