# Generated by Django 4.1.3 on 2022-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lista_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='avaliacao',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
