# Generated by Django 4.1.3 on 2022-11-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mercado_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='avaliacao',
            field=models.CharField(blank=True, default=1, max_length=3),
            preserve_default=False,
        ),
    ]
