# Generated by Django 4.1.3 on 2022-11-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lista_produto_alter_mercado_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='mercado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.mercado'),
        ),
    ]
