# Generated by Django 4.1.3 on 2022-11-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produto_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='mercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.mercado'),
        ),
    ]
